### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by ChirsKo** [pmeier/pyhyst#1]
Chris:
- [ ] Requirement Management
- [ ] SprintPlanning
- [ ] Review Comments, focus on RelayOperator
- [X] SetUp Local Environment (Git, Anaconda)
- [ ] Testconcept

Phil:
- [ ] Code Comments
- [ ] Bug Fix

Storage:
- [ ] UML Diagramm
- [ ] Project Structure (Folder: docs, test)
- [ ] Code Format (PEP8)
- [ ] Refactor floatcmp
- [ ] Teststructure/cases
- [ ] Documentation (Sphinx-doc)

**Comment by ChirsKo** [comment]
Transfered to Kanbanboard.
